#Estudio Activo
#Mon Sep 21 23:31:06 CST 2026
aciertos=48
cola=
desbloqueadas=16
errores=18
examen=true
examenIndice=16
falladas=
foco=15
focoResuelto=true
mejorRacha=18
ordenExamen=15,4,1,5,2,3,11,8,10,9,12,7,6,13,0,14
pendientes=
racha=18
reloj=66
seguidas=3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
terminado=true
total=16
ultimo=14
version=2
