#Estudio Activo
#Mon Sep 21 23:43:14 CST 2026
aciertos=25
cola=
desbloqueadas=8
errores=5
examen=true
examenIndice=8
falladas=
foco=7
focoResuelto=true
mejorRacha=11
ordenExamen=1,4,3,2,7,5,6,0
pendientes=
racha=11
reloj=30
seguidas=3,3,3,3,3,3,3,3
terminado=true
total=8
ultimo=0
version=2
