#Estudio Activo
#Fri Sep 18 19:15:33 CST 2026
aciertos=68
cola=
desbloqueadas=11
errores=13
examen=true
examenIndice=11
falladas=
foco=10
focoResuelto=true
mejorRacha=26
ordenExamen=0,6,5,9,10,1,4,8,2,7,3
pendientes=
racha=26
reloj=81
seguidas=3,3,3,3,3,3,3,3,3,3,3
terminado=true
total=11
ultimo=3
version=2
