#Estudio Activo
#Sun Sep 20 19:20:23 CST 2026
aciertos=30
cola=
desbloqueadas=10
errores=11
examen=true
examenIndice=10
falladas=
foco=9
focoResuelto=true
mejorRacha=17
ordenExamen=6,2,4,0,3,8,1,5,7,9
pendientes=
racha=17
reloj=41
seguidas=3,3,3,3,3,3,3,3,3,3
terminado=true
total=10
ultimo=9
version=2
