#Estudio Activo
#Mon Sep 21 23:47:26 CST 2026
aciertos=33
cola=
desbloqueadas=11
errores=0
examen=true
examenIndice=11
falladas=
foco=10
focoResuelto=true
mejorRacha=33
ordenExamen=2,8,5,10,6,0,3,1,7,9,4
pendientes=
racha=33
reloj=33
seguidas=3,3,3,3,3,3,3,3,3,3,3
terminado=true
total=11
ultimo=4
version=2
