#Estudio Activo
#Fri Sep 18 19:10:30 CST 2026
aciertos=15
cola=
desbloqueadas=5
errores=4
examen=true
examenIndice=5
falladas=
foco=4
focoResuelto=true
mejorRacha=13
ordenExamen=2,0,3,4,1
pendientes=
racha=13
reloj=19
seguidas=3,3,3,3,3
terminado=true
total=5
ultimo=1
version=2
