#Estudio Activo
#Tue Sep 22 10:45:12 CST 2026
aciertos=27
cola=
desbloqueadas=9
errores=4
examen=true
examenIndice=9
falladas=
foco=8
focoResuelto=true
mejorRacha=19
ordenExamen=8,6,4,0,7,5,2,1,3
pendientes=
racha=19
reloj=31
seguidas=3,3,3,3,3,3,3,3,3
terminado=true
total=9
ultimo=3
version=2
