#Estudio Activo
#Mon Sep 21 20:52:10 CST 2026
aciertos=22
cola=
desbloqueadas=7
errores=10
examen=true
examenIndice=7
falladas=
foco=6
focoResuelto=true
mejorRacha=10
ordenExamen=4,0,6,2,3,1,5
pendientes=
racha=10
reloj=32
seguidas=3,3,3,3,3,3,3
terminado=true
total=7
ultimo=5
version=2
