#Estudio Activo
#Sun Sep 20 20:04:52 CST 2026
aciertos=34
cola=
desbloqueadas=11
errores=14
examen=true
examenIndice=11
falladas=
foco=10
focoResuelto=true
mejorRacha=16
ordenExamen=9,8,6,0,5,10,1,7,4,2,3
pendientes=
racha=16
reloj=48
seguidas=3,3,3,3,3,3,3,3,3,3,3
terminado=true
total=11
ultimo=3
version=2
