#Estudio Activo
#Sun Sep 27 15:00:15 CST 2026
aciertos=0
cola=1\:REINTENTO\:11.5,0\:REINTENTO\:12.5,2\:REINTENTO\:13.5
desbloqueadas=3
errores=11
examen=false
examenIndice=0
falladas=0,1,2
foco=2
focoResuelto=false
mejorRacha=0
ordenExamen=
pendientes=
racha=0
reloj=11
reparando=-1
retiro=2
seguidas=0,0,0,0
terminado=false
total=4
ultimo=2
version=3
