#Estudio Activo
#Tue Sep 22 12:56:40 CST 2026
aciertos=14
cola=7\:REINTENTO\:25.5,8\:REINTENTO\:26.5
desbloqueadas=9
errores=11
examen=false
examenIndice=0
falladas=7,8
foco=8
focoResuelto=false
mejorRacha=6
ordenExamen=
pendientes=
racha=0
reloj=25
seguidas=2,2,2,2,2,2,2,0,0,0,0
terminado=false
total=11
ultimo=8
version=2
