#Estudio Activo
#Tue Sep 22 20:26:59 CST 2026
aciertos=29
cola=0\:FINAL\:34.0
desbloqueadas=9
errores=4
examen=true
examenIndice=2
falladas=
foco=8
focoResuelto=true
mejorRacha=21
ordenExamen=4,3,0,7,8,1,5,6,2
pendientes=
racha=21
reloj=33
reparando=-1
retiro=2
seguidas=2,2,2,3,3,2,2,2,2
terminado=false
total=9
ultimo=3
version=3
