#Estudio Activo
#Fri Sep 18 18:55:11 CST 2026
aciertos=43
cola=
desbloqueadas=14
errores=17
examen=true
examenIndice=14
falladas=
foco=13
focoResuelto=true
mejorRacha=21
ordenExamen=8,3,4,10,12,5,13,2,11,0,9,6,7,1
pendientes=
racha=21
reloj=60
seguidas=3,3,3,3,3,3,3,3,3,3,3,3,3,3
terminado=true
total=14
ultimo=1
version=2
