#Estudio Activo
#Tue Sep 22 16:18:31 CST 2026
aciertos=33
cola=
desbloqueadas=11
errores=18
examen=true
examenIndice=11
falladas=
foco=10
focoResuelto=true
mejorRacha=13
ordenExamen=2,9,7,1,0,5,10,4,6,8,3
pendientes=
racha=13
reloj=51
seguidas=3,3,3,3,3,3,3,3,3,3,3
terminado=true
total=11
ultimo=3
version=2
