#Estudio Activo
#Wed Sep 16 13:41:25 CST 2026
aciertos=0
cola=0\:NUEVA\:1.0
desbloqueadas=1
dominadas=
errores=0
falladas=
foco=0
focoResuelto=false
mejorRacha=0
pendientes=
racha=0
reloj=0
terminado=false
total=5
ultimo=-1
version=1
