#Estudio Activo
#Fri Sep 25 17:20:55 CST 2026
aciertos=2
cola=1\:REPASO\:6.0,3\:NUEVA\:7.0
desbloqueadas=4
errores=3
examen=false
examenIndice=0
falladas=0
foco=3
focoResuelto=false
mejorRacha=1
ordenExamen=
pendientes=0\:1
racha=1
reloj=5
reparando=-1
retiro=2
seguidas=0,1,1,0,0
terminado=false
total=5
ultimo=2
version=3
