#Estudio Activo
#Sun Sep 20 14:41:04 CST 2026
aciertos=0
cola=0\:REINTENTO\:3.0
desbloqueadas=1
errores=2
examen=false
examenIndice=0
falladas=0
foco=0
focoResuelto=false
mejorRacha=0
ordenExamen=
pendientes=
racha=0
reloj=2
seguidas=0
terminado=false
total=1
ultimo=0
version=2
