#Estudio Activo
#Fri Sep 18 19:22:25 CST 2026
aciertos=41
cola=
desbloqueadas=8
errores=11
examen=true
examenIndice=8
falladas=
foco=7
focoResuelto=true
mejorRacha=12
ordenExamen=6,3,0,1,5,2,7,4
pendientes=
racha=10
reloj=52
seguidas=4,3,3,4,3,3,3,4
terminado=true
total=8
ultimo=4
version=2
