#Estudio Activo
#Mon Sep 21 23:44:47 CST 2026
aciertos=27
cola=
desbloqueadas=9
errores=1
examen=true
examenIndice=9
falladas=
foco=8
focoResuelto=true
mejorRacha=27
ordenExamen=5,1,2,4,3,7,8,0,6
pendientes=
racha=27
reloj=28
seguidas=3,3,3,3,3,3,3,3,3
terminado=true
total=9
ultimo=6
version=2
